name: Construir APK de Adaptive Movil PC

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'PASO 1: Clonando el proyecto...'
        uses: actions/checkout@v4

      - name: 'PASO 2: Configurando Java y Node.js...'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 'PASO 3: Instalando Cordova...'
        run: npm install -g cordova

      # EL PASO 4 HA SIDO ELIMINADO. YA NO ES NECESARIO.

      - name: 'PASO 4 (NUEVO): Añadiendo la plataforma Android...'
        # Cordova usará automáticamente el config.xml y la carpeta www que ya existen.
        run: cordova platform add android

      - name: 'PASO 5: CONSTRUYENDO LA APK...'
        run: cordova build android --release

      - name: 'PASO 6: Subiendo la APK como Artefacto...'
        uses: actions/upload-artifact@v4
        with:
          name: Adaptive-Movil-PC-APK
          path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
