name: Construir APK de Adaptive Movil PC

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'PASO 1: Clonando el proyecto...'
        uses: actions/checkout@v4

      - name: 'PASO 2: Configurando Java y Node.js...'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 'PASO 3: Instalando Cordova...'
        run: npm install -g cordova

      # ¡¡¡LA LÓGICA CORRECTA!!!
      # Como tu repositorio ya tiene la estructura correcta (www/, config.xml),
      # simplemente le decimos a Cordova que cree el proyecto aquí mismo.
      # Usamos 'cordova create .' para decirle "crea el proyecto en la carpeta actual".
      - name: 'PASO 4: Inicializando el proyecto Cordova...'
        run: |
          # Creamos un proyecto de Cordova en la carpeta actual, usando los archivos existentes.
          # Primero, movemos nuestros archivos a una carpeta temporal.
          mkdir ../temp_files
          mv www ../temp_files/
          mv config.xml ../temp_files/
          # Creamos el proyecto Cordova.
          cordova create . com.adaptivemovilpc.gel "Adaptive Movil PC"
          # Borramos la carpeta 'www' y 'config.xml' por defecto.
          rm -rf www config.xml
          # Movemos nuestros archivos de vuelta.
          mv ../temp_files/www .
          mv ../temp_files/config.xml .

      - name: 'PASO 5: Añadiendo la plataforma Android...'
        run: cordova platform add android

      - name: 'PASO 6: CONSTRUYENDO LA APK...'
        run: cordova build android --release

      - name: 'PASO 7: Subiendo la APK como Artefacto...'
        uses: actions/upload-artifact@v4
        with:
          name: Adaptive-Movil-PC-APK
          path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
